🐎🐛 Optimized querying of database; Refactored code so it's more readable; etc.
qbcore-framework/qb-weed pull request #27
Opened 2022-01-14 17:10 UTC by Kiracorp

This code is tested with the latest qb libraries.

Performance changes:

    Replaced PlaceObjectOnGroundProperly() with statically coded offsets for each plant prop (they spawn in at different heights) configured in config.lua
    Plants will no longer spawn on top of each other or in the ceiling, instead they will always spawn at the level of the player's feet when placed
    Plants now rerender only when necessary
    Database is only queried when necessary
    API is cleaned up between the server and the client
    Now maintains references to objects that are spawned so they can be deleted without finding them again based on coordinates

Interactional changes:

    You can now remove a plant before it's ready to harvest or dead so you don't get stuck
    Increased minimum distance between plants so you can always walk between them
    Harvesting weed now requires the same number of bags you get from the plant when harvesting
    Nutrition and health below a 50% now displays red instead of blue
    Distance to a plant must be half the minimum distance to place the plant in order to do an action to it (harvest, remove, fertilize)

2022-01-23 01:07 UTC, evanillaa commented
Conflicts

2022-01-23 01:09 UTC, Kiracorp commented
Yeah, pull the files from my repo to merge. I can't resolve the conflict here. Try it on a fresh server.

2022-01-23 01:09 UTC, Kiracorp commented
It should be a lot better than what is here.

2022-01-23 01:12 UTC, Kiracorp commented
I basically took what was there and reorganized it and added a bunch of QOL stuff.

2022-02-06 21:02 UTC, mk3ext requested changes
Better to use the new MySQL calls instead; please check https://github.com/overextended/oxmysql/issues/77

This is mainly due to already using MySQL calls in this code base, and keeping it all the same is neater

2022-02-11 01:44 UTC, jnccloud commented
I have been running this branch for a few weeks now. I've been noticing a trend of 'Reliable Network Event Overflow' disconnects. I finally sat in someone's house that had no weed growing (they have weed in other houses, not nearby) and received the error myself. Here is some debugging info:
![image](https://user-images.githubusercontent.com/58707473/153525391-3c0804c5-4def-4801-ae25-356318d77f14.png)
```
-- Event triggered by the server to refresh model after stage update, manually maintains state of houseProps
RegisterNetEvent('qb-weed:client:refreshPlantProp', function(id, newStage)
    if insideHouse() then
        if housePlants[id] == nil then
            updateHousePlant(id)
        else
            housePlants[id].stage = newStage
            housePlants[id].progress = 0
            unrenderPlant(id)
            renderPlant(id)
        end
    end
end)
```
![image](https://user-images.githubusercontent.com/58707473/153525458-610b6b93-1a4c-4d54-a34e-6d84f3f9ae25.png)

It definitely seems to be the culprit to this issue on my end. I was watching the neteventlog and as it crashed it was weed related events (the callbacks are most likely the same as you see above, but I wasn't running a profiler when I crashed)

![image](https://user-images.githubusercontent.com/58707473/153525534-8c2cf13e-ce80-47cb-9ff0-b6ed666c29e4.png)

I like the refactor but I believe this issue is a large problem. It's really noticeable 70+ players.

2022-02-11 04:38 UTC, Kiracorp commented
Newest commit should address 'Reliable Network Event Overflow' disconnects. On the growth tick, the script now updates all plants stages in the database first and then tells every client to update every plant prop at once. Similarly, on the nutrition and health tick, the script updates the database with the new plant stats and then tells every client to update every house plant as all the stats should be updated.

Also changed oxmysql calls to MySQL calls.

2022-02-11 04:52 UTC, Kiracorp commented
A few other problems I know of with this refactor are that you can still place plants inside walls, you can place plants floating in air if you stand on a prop like a couch or a counter, and currently the server side is telling every client to do every update to a plant.

This last one is due to the fact that if someone is in your house and some other event occurs besides the growth or prop tick such as you remove or place a plant for example, you want them to be able to see the change you made. Could possibly check for players within a certain radius of the plant that was altered by a player event but I haven't implemented that.

2022-02-11 05:36 UTC, Kiracorp commented
Hopefully that commit addresses part of the problem of unnecessary database queries when a player updates a plant in a house when you are in a different house. Server now to tells the client what house the plant is in that needs to be updated. The growth and nutrition tick still apply to all clients and all houses but only query the database if the player is in a house.

2022-02-11 15:40 UTC, jnccloud commented
Thanks for the fast response! I am running this again and so far so good. The callbacks have decreased TREMENDOUSLY. I did notice something I thought was missing, there doesn't seem to be a prune for the dead plants? I just added a quick delete statement into the tick but I figured it might make more sense on resource start to delete the dead plants? Originally I had 1700 dead plants I had to delete from my database (running the version from last night).

2022-02-11 15:44 UTC, Kiracorp commented
Yeah, I might put that in as an option in the config. I thought probably a good idea to have it on by default.

2022-02-11 16:25 UTC, Kiracorp commented
Probably the best way to do it would just be to delete any plants from the database at startup that have 0 health.

2022-02-11 19:05 UTC, Kiracorp commented
That should fix the problem of the server spamming SQL every growth or nutrition tick to update all the plants.

2022-04-07 04:40 UTC, closed without merging