Fix PT language auto load
qbcore-framework/qb-weed pull request #69
Opened 2023-11-15 13:18 UTC by Swellington-Soares

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2024-01-11 21:19 UTC, citRaTTV requested changes

2024-01-11 21:19 UTC, citRaTTV commented on client/main.lua
> +        print('L24', house, json.encode(plants))
This print should be removed

2024-01-11 21:19 UTC, citRaTTV commented on client/main.lua
> +            if currentHouse then
This if statement can be combined with the one on L#35

2024-01-14 17:18 UTC, Swellington-Soares commented on client/main.lua
> +        print('L24', house, json.encode(plants))
Thank you.

2024-01-14 21:10 UTC, citRaTTV approved these changes

2024-01-14 23:23 UTC, merged